/**
 * Cryptographic approval token for owner-approved high-risk actions.
 * Replaces the spoofable [OWNER_APPROVED] string marker with HMAC verification.
 */

import { createHmac, randomBytes } from 'node:crypto';

// Secret rotates per process start — tokens from prior runs are invalid
const SECRET = randomBytes(32).toString('hex');

/**
 * Generate an HMAC approval token for a task.
 * Called when the owner explicitly approves a high-risk action.
 */
export function generateApprovalToken(taskId: string, floorId: string): string {
  const payload = `${taskId}:${floorId}:${Date.now()}`;
  const hmac = createHmac('sha256', SECRET).update(payload).digest('hex');
  return `${payload}:${hmac}`;
}

/**
 * Verify that an approval token is valid (was generated by this process).
 */
export function verifyApprovalToken(token: string): boolean {
  if (!token) return false;
  const parts = token.split(':');
  if (parts.length < 4) return false;

  const hmac = parts.pop()!;
  const payload = parts.join(':');
  const expected = createHmac('sha256', SECRET).update(payload).digest('hex');

  // Constant-time comparison to prevent timing attacks
  if (hmac.length !== expected.length) return false;
  let diff = 0;
  for (let i = 0; i < hmac.length; i++) {
    diff |= hmac.charCodeAt(i) ^ expected.charCodeAt(i);
  }
  return diff === 0;
}
